You may inspect this notebook on my [jovian profile](https://jovian.ai/sokoly35/module1-pytorch-basics)!

In [ ]:
!pip install torch

In [2]:
!pip install numpy

In [3]:
import torch
import numpy as np

# Exercise 1

## a)

In [15]:
# Defining 1D tensor
tensor1d = torch.tensor([1, 2, 3, 4])
# If we want it to have float dtype, we must to add dot to at least one number
tensor1d_float = torch.tensor([1., 2, 3, 4])

# Defining 2D tensor
tensor2d = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
# If we want it to have float dtype, we must to add dot to at least one number
tensor2d_float = torch.tensor([[1., 2, 3, 4], [5, 6, 7, 8]])

# Defining 3D tensor
tensor3d = torch.tensor([[[1., 2, 3, 4], [5, 6, 7, 8]],
                         [[9, 10, 11, 12], [13, 14, 15, 16]]])
# If we want it to have float dtype, we must to add dot to at least one number
tensor3d_float = torch.tensor([[[1., 2, 3, 4], [5, 6, 7, 8]],
                         [[9, 10, 11, 12], [13, 14, 15, 16]]])

In [16]:
print(f"Data type of 1D tensor {tensor1d.dtype}, Shape {tensor1d.shape}")
print(f"Data type of 1D float tensor {tensor1d_float.dtype}, Shape {tensor1d_float.shape}")
print()
print(f"Data type of 2D tensor {tensor2d.dtype}, Shape {tensor2d.shape}")
print(f"Data type of 2D float tensor {tensor2d_float.dtype}, Shape {tensor2d_float.shape}")
print()
print(f"Data type of 3D tensor {tensor3d.dtype}, Shape {tensor3d.shape}")
print(f"Data type of 3D float tensor {tensor3d_float.dtype}, Shape {tensor3d_float.shape}")

Data type of 1D tensor torch.int64, Shape torch.Size([4])
Data type of 1D float tensor torch.float32, Shape torch.Size([4])

Data type of 2D tensor torch.int64, Shape torch.Size([2, 4])
Data type of 2D float tensor torch.float32, Shape torch.Size([2, 4])

Data type of 3D tensor torch.float32, Shape torch.Size([2, 2, 4])
Data type of 3D float tensor torch.float32, Shape torch.Size([2, 2, 4])


## b)

In [19]:
## Defining numpy arrays
# If we want dtype to be float we need to pass float in arrange
numpy1d = np.arange(4.)
# Reshaping to 2D and 3D tensors
numpy2d = np.arange(8).reshape(2, 4)
numpy3d = np.arange(16).reshape(2, 2, 4)

# Converting numpy arrays to torch tensors
torch1d = torch.from_numpy(numpy1d)
torch2d = torch.from_numpy(numpy2d)
torch3d = torch.from_numpy(numpy3d)

In [20]:
print(f"Data type of 1D tensor {torch1d.dtype}, Shape {torch1d.shape}")
print()
print(f"Data type of 2D tensor {torch2d.dtype}, Shape {torch2d.shape}")
print()
print(f"Data type of 3D tensor {torch3d.dtype}, Shape {torch3d.shape}")

Data type of 1D tensor torch.float64, Shape torch.Size([4])

Data type of 2D tensor torch.int64, Shape torch.Size([2, 4])

Data type of 3D tensor torch.int64, Shape torch.Size([2, 2, 4])


# Exercise 2

In [51]:
# Defining 1D tensor (3, )
tensor1d = torch.tensor([3., 4, 5])

# Defining 2D tensor of shape (3, 4)
tensor2d = torch.tensor([[1., 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])

# We use numpy to create 3D tensor of shape (4, 3, 3)
numpy3d = np.arange(1., 37).reshape(4, 3, 3)
# We may also pass it to torch.tensor function instead from_numpy
# but we need to specify dtype to float32 because by default it is float64
# If so, then our multiplication will fail
tensor3d = torch.tensor(numpy3d, dtype=torch.float32)
# The result will be float tensor
print(f"Data type of 3D tensor {tensor3d.dtype}, Shape {tensor3d.shape}")

Data type of 3D tensor torch.float32, Shape torch.Size([4, 3, 3])


In [52]:
# mult1 = tensor1d  @ tensor2d
print(mult1, mult1.shape)

tensor([ 68.,  80.,  92., 104.]) torch.Size([4])


In [53]:
mult2 = tensor2d.T @ tensor3d
print(mult2, mult2.shape)

tensor([[[ 84.,  99., 114.],
         [ 96., 114., 132.],
         [108., 129., 150.],
         [120., 144., 168.]],

        [[219., 234., 249.],
         [258., 276., 294.],
         [297., 318., 339.],
         [336., 360., 384.]],

        [[354., 369., 384.],
         [420., 438., 456.],
         [486., 507., 528.],
         [552., 576., 600.]],

        [[489., 504., 519.],
         [582., 600., 618.],
         [675., 696., 717.],
         [768., 792., 816.]]]) torch.Size([4, 4, 3])


In [58]:
mult3 = tensor3d @ tensor2d
print(mult3, mult3.shape)

tensor([[[ 38.,  44.,  50.,  56.],
         [ 83.,  98., 113., 128.],
         [128., 152., 176., 200.]],

        [[173., 206., 239., 272.],
         [218., 260., 302., 344.],
         [263., 314., 365., 416.]],

        [[308., 368., 428., 488.],
         [353., 422., 491., 560.],
         [398., 476., 554., 632.]],

        [[443., 530., 617., 704.],
         [488., 584., 680., 776.],
         [533., 638., 743., 848.]]]) torch.Size([4, 3, 4])


In [59]:
mult4 = tensor1d @ tensor3d @ tensor2d
print(mult4, mult4.shape)

tensor([[1086., 1284., 1482., 1680.],
        [2706., 3228., 3750., 4272.],
        [4326., 5172., 6018., 6864.],
        [5946., 7116., 8286., 9456.]]) torch.Size([4, 4])


# Exercise 3

In [64]:
# Defining 1D pytorch tensor
tensor1d = torch.arange(4.)
# Defining 2D and 3D pytorch tensors. Using arange obligatory us to reshape tensor
tensor2d = torch.arange(8.).reshape(2, 4)
tensor3d = torch.arange(16).reshape(2, 2, 4)
# Inspecting shapes of tensors
print(tensor1d.shape, tensor2d.shape, tensor3d.shape)

torch.Size([4]) torch.Size([2, 4]) torch.Size([2, 2, 4])


In [68]:
numpy1d = tensor1d.numpy()
numpy2d = tensor2d.numpy()
numpy3d = tensor3d.numpy()
print(f'1D array dtype: {type(numpy1d)}, Its shape {numpy1d.shape}')
print(f'1D array dtype: {type(numpy2d)}, Its shape {numpy2d.shape}')
print(f'1D array dtype: {type(numpy3d)}, Its shape {numpy3d.shape}')

1D array dtype: <class 'numpy.ndarray'>, Its shape (4,)
1D array dtype: <class 'numpy.ndarray'>, Its shape (2, 4)
1D array dtype: <class 'numpy.ndarray'>, Its shape (2, 2, 4)


# Exercise 4

In [77]:
# Setting random seed for reproducibility
torch.manual_seed(7)

In [78]:
# Generating random tensor from standard normal distribution 
normal_random_tensor = torch.randn(3, 1, 2)
print(normal_random_tensor)
normal_random_tensor.shape

tensor([[[-0.1468,  0.7861]],

        [[ 0.9468, -1.1143]],

        [[ 1.6908, -0.8948]]])


torch.Size([3, 1, 2])

In [79]:
# Generating random tensor from uniform distribution
uniform_random_tensor = torch.rand(3, 1, 2)
print(uniform_random_tensor)
uniform_random_tensor.shape

tensor([[[0.2868, 0.2063]],

        [[0.4451, 0.3593]],

        [[0.7204, 0.0731]]])


torch.Size([3, 1, 2])

# Exercise 5

In [84]:
# Generating 3 random tensors
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(3, 4)
tensor3 = torch.randn(3, 4)

# Appending tensors on each other
cat1 = torch.cat([tensor1, tensor2, tensor3])
print(f'Concatenating along 0 dim, shape: {cat1.shape}')
# Horizontally stacking matrices
cat2 = torch.cat([tensor1, tensor2, tensor3], 1)
print(f'Concatenating along 1 dim, shape: {cat2.shape}')

Concatenating along 0 dim, shape: torch.Size([9, 4])
Concatenating along 1 dim, shape: torch.Size([3, 12])


# Exercise 6

In [86]:
# Defining tensor (4, 5)
tensor = torch.arange(20).reshape(4, 5)
tensor

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [91]:
# Selecting 3rd row
tensor[2, :]

tensor([10, 11, 12, 13, 14])

In [93]:
# Selecting 5th column
tensor[:, 4]

tensor([ 4,  9, 14, 19])

In [94]:
# It is also the last column
tensor[:, -1]

tensor([ 4,  9, 14, 19])

In [95]:
# Selecting value from 2nd row and 3rd column
tensor[1, 2]

tensor(7)

In [99]:
# Selecting values from 1st row and 3rd to 5th columns
tensor[0, 2:5]

tensor([2, 3, 4])

# Exercise 7

In [114]:
# Defining sample tensor (3, 3)
tensor = torch.arange(-3., 6).reshape(3, 3)
tensor

tensor([[-3., -2., -1.],
        [ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])

In [104]:
# Number of elements
tensor.numel()

9

In [106]:
# Creating zero tensor of shape (2, 2)
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [108]:
# Creating ones tensor of shape (2, 2)
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [110]:
# Create tensor of n equally distributed points
torch.linspace(0, 1, 5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [111]:
# Creates filled with uninitialized values
torch.empty(4, 4)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.9494e+20, 3.0969e-41, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 5.6052e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [112]:
# Creates tensor of given shape filled with given value
torch.full((3, 3), 4)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [121]:
# Function returns new tensor of specified shape
tensor.view(1, -1)

tensor([[-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.]])

In [123]:
# Function returns heaviside function applied to a tensor
# It is important that boundary have to have the same dtype as tensor
# Be aweare that function behave unexpectedly around boundary
torch.heaviside(tensor, torch.tensor(3.))

tensor([[0., 0., 0.],
        [3., 1., 1.],
        [1., 1., 1.]])

In [133]:
temp = tensor.reshape(1, 3, 3)
print(temp.shape)
# Squeeze removes all dimensions which equals 1
torch.squeeze(temp).shape

torch.Size([1, 3, 3])


torch.Size([3, 3])

In [134]:
# Function draws random permutation from 0 to n-1
torch.randperm(5)

tensor([4, 0, 3, 1, 2])

In [137]:
# Index of max value in tensor
index = torch.argmax(tensor)

In [140]:
# Accesing value of tensor
index.item()

8

In [144]:
# Tensor cumulative sum
torch.cumsum(tensor, 0)

tensor([[-3., -2., -1.],
        [-3., -1.,  1.],
        [ 0.,  3.,  6.]])

In [146]:
# If dimension is >1 then return main diagonal
torch.diag(tensor)

tensor([-3.,  1.,  5.])

In [148]:
# If tensor is 1D then it returns diagonal matrix
torch.diag(torch.diag(tensor))

tensor([[-3.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  5.]])

In [151]:
# Flattening tensor
tensor.flatten()

tensor([-3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

# Exercise 8

In [170]:
# Defining torch scalars, gradients work only on scalars
x = torch.tensor(3.)
# Defining scalars which enables autograd mechanism
y = torch.tensor(4., requires_grad=True)
w = torch.tensor(5., requires_grad=True)
# Defining equation
z = w * x + y
# Calculating gradients
z.backward()

In [171]:
print(f"dz/dx = {x.grad}. Autograd is False")
print(f"dz/dy = {y.grad}. It is derrivative of constant, which equals 1")
print(f"dz/dw = {w.grad}, because it should be equal x")

dz/dx = None. Autograd is False
dz/dy = 1.0. It is derrivative of constant, which equals 1
dz/dw = 3.0, because it should be equal x


In [173]:
# Defining torch scalars, gradients work only on scalars
x = torch.tensor(3.)
# Defining scalars which enables autograd mechanism
y = torch.tensor(4., requires_grad=True)
w = torch.tensor(5., requires_grad=True)
# Defining equation, this time we will raise x to power
z = w * x ** 2 + y
# Calculating gradients
z.backward()

In [175]:
print(f"dz/dx = {x.grad}. Autograd is False")
print(f"dz/dy = {y.grad}. It is derrivative of constant, which equals 1")
print(f"dz/dw = {w.grad}, because it should be equal x * x")

dz/dx = None. Autograd is False
dz/dy = 1.0. It is derrivative of constant, which equals 1
dz/dw = 9.0, because it should be equal x * x


In [176]:
# Defining torch scalars, gradients work only on scalars
x = torch.tensor(3.)
# Defining scalars which enables autograd mechanism
y = torch.tensor(4., requires_grad=True)
w = torch.tensor(5., requires_grad=True)
# Defining equation, this time we will raise w to power
z = w ** 2 * x + y
# Calculating gradients
z.backward()

In [180]:
print(f"dz/dx = {x.grad}. Autograd is False")
print(f"dz/dy = {y.grad}. It is derrivative of constant, which equals 1")
print(f"dz/dw = {w.grad}, because it should be equal x * 2*w")

dz/dx = None. Autograd is False
dz/dy = 1.0. It is derrivative of constant, which equals 1
dz/dw = 30.0, because it should be equal x * 2*w


In [181]:
# Defining torch scalars, gradients work only on scalars
x = torch.tensor(3.)
# Defining scalars which enables autograd mechanism
y = torch.tensor(4., requires_grad=True)
w = torch.tensor(5., requires_grad=True)
# Defining equation, this time we will calculates exponent from y
z = w ** 2 * x + torch.exp(y)
# Calculating gradients
z.backward()

print(f"dz/dx = {x.grad}. Autograd is False")
print(f"dz/dy = {y.grad}. It equals exp(y)")
print(f"dz/dw = {w.grad}, because it should be equal x * 2*w")

dz/dx = None. Autograd is False
dz/dy = 54.598148345947266. It equals exp(y)
dz/dw = 30.0, because it should be equal x * 2*w


# Commiting notebook to jovian

In [32]:
!pip install jovian --quiet

In [34]:
import jovian

<IPython.core.display.Javascript object>

In [35]:
# Execute this to save new versions of the notebook
jovian.commit('Solving exercise from 1. to 8.',
              git_message="Completing module 1",
              project="module1-pytorch-basics")

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Updating notebook "sokoly35/module1-pytorch-basics" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/sokoly35/module1-pytorch-basics


'https://jovian.ai/sokoly35/module1-pytorch-basics'